# Generated by Django 5.0.4 on 2024-10-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='air_humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='air_temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='ambient_light',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='ground_humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='irrigate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='lights',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
