# Generated by Django 5.0.4 on 2024-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telemetry_air_humidity_telemetry_air_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='air_temperature',
            field=models.IntegerField(default=-1),
        ),
    ]
