# Generated by Django 5.0.4 on 2024-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_telemetry_air_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='irrigate_since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
